"""Bake a local land mask from Natural Earth's public-domain 10m coastline.

Run with Python and Pillow: python3 scripts/make-hongkong-map.py
"""
import base64
import json
from pathlib import Path
from urllib.request import urlopen
from PIL import Image, ImageDraw

SOURCE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_land.geojson'
WEST, SOUTH, EAST, NORTH = 113.5, 21.6, 114.8, 22.9
SIZE = 1040
with urlopen(SOURCE) as response:
    features = json.load(response)['features']
image = Image.new('1', (SIZE, SIZE))
for feature in features:
    geometry = feature['geometry']
    polygons = geometry['coordinates'] if geometry['type'] == 'MultiPolygon' else [geometry['coordinates']]
    for polygon in polygons:
        outer = polygon[0]
        if (max(p[0] for p in outer) < WEST or min(p[0] for p in outer) > EAST
                or max(p[1] for p in outer) < SOUTH or min(p[1] for p in outer) > NORTH):
            continue
        mask = Image.new('1', (SIZE, SIZE))
        draw = ImageDraw.Draw(mask)
        for i, ring in enumerate(polygon):
            points = [((lon - WEST) / (EAST - WEST) * SIZE,
                       (NORTH - lat) / (NORTH - SOUTH) * SIZE) for lon, lat in ring]
            draw.polygon(points, fill=1 if i == 0 else 0)
        # Union polygons without letting one polygon's holes erase another.
        from PIL import ImageChops
        image = ImageChops.lighter(image, mask)
result = dict(w=SIZE, h=SIZE, west=WEST, north=NORTH, step=(EAST-WEST)/SIZE,
              bits=base64.b64encode(image.tobytes()).decode())
output = Path(__file__).resolve().parents[1] / 'assets/hongkong-map.js'
output.write_text('/** Hong Kong land mask. Generated by scripts/make-hongkong-map.py.\n'
                  ' * Source: Natural Earth 10m land (public domain), ' + SOURCE + '\n */\n'
                  'export const HONG_KONG = ' + json.dumps(result, separators=(',', ':')) + ';\n')
print(f'Wrote {output} ({output.stat().st_size} bytes)')
